services:
  - type: static_site
    name: Moon
    buildCommand: "cd apps/web && pnpm install && pnpm build && cp config.json webapp/config.json && echo 'Config copied to webapp'"
    publishPath: apps/web/webapp
    envVars:
      - key: NODE_VERSION
        value: "22"
