services:
  - type: static_site
    name: Moon
    buildCommand: "cd apps/web && pnpm install && pnpm build"
    publishPath: apps/web/webapp
    envVars:
      - key: NODE_VERSION
        value: "22"
